# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'GithubIssueTracker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxCocoa', '~> 3.0.0'
  pod 'Moya-ModelMapper/RxSwift', '~> 4.0.0'
  pod 'RxOptional'
  pod 'R.swift'
  pod "RxSwiftUtilities"
  pod 'SnapKit', '~> 3.2.0'

  target 'GithubIssueTrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GithubIssueTrackerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
